### ISSUE TITLE
Question for the Assignment-5 (Quant)

### ISSUE THREAD

**Issue by jiwonpark1994** [SES-5215-F2020/jiwonpark-quant#5]
Hello Carole,

I had an error while completing the quant assignment-5 (https://ses-5215-f2020.github.io/jiwonpark-quant/Assignment-5%20(Quant).Rmd) that I couldn't figure out the reason why. The problematic code is line 109~127, which is trying to compare two regression models. The error message is **(Error: Assigned data `x$coeftable[, lci_lab]` must be compatible with existing data. x Existing data has 12 rows. x Assigned data has 14 rows. ℹ Only vectors of size 1 are recycled. Backtrace:)** 

I was trying to address this issue during office hours with Sara, and she also tried this code on her computer thereafter, but we couldn't find the solution. Could you please look at what's wrong with the code? I also attach the CSV used in the Rmd file. 

Thank you always,
Jiwon

[tractMA2018_3rd.csv.zip](https://github.com/SES-5215-F2020/jiwonpark-quant/files/5323858/tractMA2018_3rd.csv.zip)

**Comment by c-voulgaris** [comment]
Hi Jiwon,

The problem is that your sample only includes one tract in the "other" category for majority race. So when you try to interact race with income, there's no variation in income, so it can't find the relationship between income and pct_tenure that would only apply to the other category. That's why there is an NA value as a coefficient in the Model 4 results (along with the note that a variable is omitted because of a singularity), and that NA value is giving you an error when you run the `export_summs()` function.

Another issue is that all of your "no majority" tracts have a population of zero - I would suggest filtering those out.

Some alternatives to consider:

You could collapse the race categories to just two categories "hispanic" and "not hispanic" or "white" and "not white"

You could do a different interaction - interacting majority transportation with income won't cause a problem.

You could just leave out model 4. You only need to try two different models for this assignment.

I'm happy to talk further about this during our office hours meeting in about an hour.
